# Generated by Django 3.1 on 2020-08-21 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity_periods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intime', models.TimeField(max_length=20)),
                ('out_time', models.TimeField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.IntegerField(default=0)),
                ('Real_name', models.CharField(max_length=100)),
                ('tz', models.CharField(max_length=50)),
                ('activity', models.ForeignKey(default=1, max_length=200, on_delete=django.db.models.deletion.CASCADE, to='app1.activity_periods')),
            ],
        ),
    ]
